### PR TITLE
Various build fixes for GCC and Clang

### PR DESCRIPTION
**Pull request by rtiangha**
Here are some fixes I encountered when I was playing around trying to upgrade some of the submodules. Should be enough for you guys to reactivate the msys2 build workflow.

### CODE REVIEW

**Comment by Ishan09811** [comment]
@rtiangha 
Can you also enable the msys2 build in workflow?

**Comment by rtiangha** [comment]
I mean I could, but it'd be better for someone with repo access to run a `git revert f323ff8c63ca6f899b7500f3ad11c8745713e1cc` so that people can look at the log and know that the temporary fix is done.

**Comment by rtiangha** [comment]
Ah, sorry for the spam. I just figured out how to use the Actions tab with this project; should be able to hack away at this on my own time now. I didn't realize things with the Windows GUI were tied so closely to Visual Studio that some porting would be needed to work under Clang, lol. I'll do my best to figure out how to fix things.

**Comment by rtiangha** [comment]
Oh, I guess that last commit did it. I've got a working msys2 executable on my end. Should be good to go.

**Pull request merged**
