### PR TITLE
Fix GPL violations and start anew

### PR DESCRIPTION
**Pull request by nyaaaaaaaaaaaaaaaaaaaaaaaaaaaaa420**
Fellow developers,

I want to address the elephant in the room. We've faced a setback, and accusations have been made. But I want to emphasize that setbacks are not defeats. They are opportunities for growth, for improvement, and for proving our integrity.

I beliebe we should embark on a journey of rebuilding Lemonade, with nothing but our own ingenuity, creativity, and hard work.

Starting anew means we get to redefine ourselves. We get to demonstrate our commitment to transparency, honesty, and respect for intellectual property. We have the chance to showcase our talents, not by standing on the shoulders of others, but by standing tall on the foundation of our own originality and hard work.

I believe in each and every one of you. I believe in our collective ability to rise above challenges, to overcome obstacles, and to emerge stronger and better than before. Let's channel our passion, our dedication, and our expertise into this fresh start.

Together, we will rebuild Lemonade, not just as an emulator, but as a testament to our integrity, our professionalism, and our unwavering commitment to excellence. Let's turn this setback into a comeback story that will inspire others and make us proud.

So let's roll up our sleeves, dive into the code, and let our creativity flow freely. This is our chance to shine, to make Lemonade the best it can be, and to prove to the world that we are capable of greatness.

Thank you for your hard work, your dedication, and your unwavering commitment to our shared vision. Let's make Lemonade rise again, stronger, sweeter, and more refreshing than ever before.

Onward and upward! NYAAAAAAAAAA !!! :3

### CODE REVIEW

**Comment by JaffaCat** [comment]
Looks good to me, developers please merge this.

**Comment by Gamer64ytb** [comment]
You guys are terrible. This is shocking how bad this went for some commits.

I dont know why did I ever go back to programming if I get received like this. Horrible.

**Comment by MisterSheeple** [comment]
I think it's extremely telling that in the Lemonade discord, you said you were going to merge it, and only stopped because people pointed out to you that it's a troll.

If you don't read PRs before you merge them, you have no right to be running a project on GitHub.

**Comment by JaffaCat** [comment]
> I think it's extremely telling that in the Lemonade discord, you said you were going to merge it, and only stopped because people pointed out to you that it's a troll.
> 
> If you don't read PRs before you merge them, you have no right to be running a project on GitHub.

Strongly agree with this point.

**Comment by Gamer64ytb** [comment]
I didnt even merge it.

**Comment by BlurrySquire** [comment]
deleting comments? that doesnt look good.

**Comment by JaffaCat** [comment]
"ChatGPT, how do I disable logging in GitHub comments?"

**Pull request closed without merging**
